name: Production Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Mark Deployment
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://chat-app-czo3.onrender.com # 👈 your Render URL here

    steps:
      - name: Deployed via Render
        run: echo "Deployed to production via Render"
